name: Deploy Mawqed Production

on:
  push:
    branches:
      - master

concurrency:
  group: mawqed-production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/mawqed_key
          chmod 600 ~/.ssh/mawqed_key

          ssh-keyscan -p "${{ secrets.SERVER_PORT }}" \
            "${{ secrets.SERVER_HOST }}" \
            >> ~/.ssh/known_hosts

      - name: Deploy Mawqed
        run: |
          ssh \
            -i ~/.ssh/mawqed_key \
            -p "${{ secrets.SERVER_PORT }}" \
            "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" \
            "/var/www/apps/mawqed/deploy.sh"